# Generated by Django 4.2.1 on 2023-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
