# Generated by Django 4.2.1 on 2023-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_purchased_order_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
